# Generated by Django 4.1.2 on 2022-10-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=60, verbose_name='Name and surname')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email address')),
                ('password', models.CharField(max_length=60, verbose_name='Password')),
            ],
        ),
    ]
