# Generated by Django 4.1.2 on 2022-10-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
