# Generated by Django 4.1.2 on 2022-11-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_hr_alter_myuser_email_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(error_messages={'email': 'Alredy signed up, sign in insted'}, max_length=30, unique=True, verbose_name='Email address'),
        ),
    ]
