# Generated by Django 4.1.2 on 2022-11-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_myuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('IT', 'IT'), ('Marketing', 'MARKETING'), ('Construction', 'CONSTRUCTION'), ('Engineering', 'ENGINEERING'), ('Education', 'EDUCATION'), ('Finance', 'FINANCE'), ('Health care', 'HEALTH_CARE'), ('Media', 'MEDIA')], default='Education', max_length=12, verbose_name='Industry field')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Salary')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('company', models.CharField(max_length=50, verbose_name='Company name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Email address'),
        ),
    ]
